enum VimCommand: Equatable {
    case open
    case openInNewTab
    case closeTab
    case restoreClosedTab
    case nextTab
    case previousTab
    case scrollDown
    case scrollUp
    case largeScrollDown
    case largeScrollUp
    case scrollLeft
    case scrollRight
    case pageDown
    case pageUp
    case firstPage
    case lastPage
    case jumpToPage(Int)
    case jumpBack
    case jumpForward
    case beginSearch
    case searchNext
    case searchPrevious
    case toggleOutline
    case copySelection
    case highlightSelection
    case cycleHighlightColor
    case explainHighlightSelection
    case zoomIn
    case zoomOut
    case zoomPageFit
    case zoomFit
}
